sonar.projectKey=null-pointer-sch_internal-platform-api
sonar.organization=null-pointer-sch

# Source and test paths
sonar.sources=backend/app,frontend/src/app
sonar.tests=backend/tests,frontend/src/app
sonar.test.inclusions=backend/tests/**,frontend/src/**/*.spec.ts

# Encoding
sonar.sourceEncoding=UTF-8

# Coverage reports
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/envctl-ui/lcov.info
